### ISSUE TITLE
Documentation for PhaseLockingCorrelation transform shows BandSignal implementation

### ISSUE THREAD

**Issue by chris7neves** [torcheeg/torcheeg#82]
The documentation page for the PhaseLockingCorrelation class shows the instantiation of a BandSignal object instead of a PhaseLockingCorrelation object (https://torcheeg.readthedocs.io/en/v1.1.0/generated/torcheeg.transforms.PhaseLockingCorrelation.html).

Included in this issue is a screenshot with the problem displayed. 

![image](https://github.com/torcheeg/torcheeg/assets/38571540/ccf30077-aefd-40db-8104-68914e95f431)

**Comment by tczhangzhi** [comment]
Thank you for your report, you are right, the example should be modified to:
```
transform = PhaseLockingCorrelation()
transform(eeg=np.random.randn(32, 128))['eeg'].shape
>>> (1, 32, 32)
```
Would you be willing to create a pull request that modifies this [line](https://github.com/torcheeg/torcheeg/blob/2b617a3bbda19d807eb57487a87fbedea055aef5/torcheeg/transforms/numpy/correlation.py#L94)?
Otherwise, I will revise it in the next version.

**Comment by tczhangzhi** [comment]
Fixed: https://github.com/torcheeg/torcheeg/blob/develop/torcheeg/transforms/numpy/correlation.py#L94
